#!/bin/sh
max=95000000
files=$(git diff --cached --name-only)
for f in $files; do [ -f "$f" ] || continue; s=$(wc -c <"$f"); if [ "$s" -gt "$max" ]; then echo "ERROR: $f is ${s} bytes (>95MB)."; exit 1; fi; done
